# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "boxcutter/centos71"
  config.vm.provision :shell, path: "bootstrap_centos7.sh", privileged:false
  config.vm.synced_folder "../../", "/home/vagrant/packetgraph", create: true
end
