# Finds packetgraph-antispoof includes and library
# Defines:
#  LIBPACKETGRAPH-ANTISPOOF_INCLUDE_DIR
#  LIBPACKETGRAPH-ANTISPOOF_LIBRARY
#  LIBPACKETGRAPH-ANTISPOOF_FOUND

if (NOT "${PG_ANTISPOOF}" STREQUAL "")
	set(LIBPACKETGRAPH-ANTISPOOF_INCLUDE_DIR ${PG_ROOT}/antispoof)
	set(LIBPACKETGRAPH-ANTISPOOF_LIBRARY "${PG_USER_ANTISPOOF_BUILD}/libpacketgraph-antispoof.a")
	set(LIBPACKETGRAPH-ANTISPOOF_LIBRARY_SHARED "${PG_USER_ANTISPOOF_BUILD}/libpacketgraph-antispoof.so")
	set(LIBPACKETGRAPH-ANTISPOOF_FOUND 1)
    return()
endif()

if (NOT "${PG_ROOT_PATH}" STREQUAL "")
	set(LIBPACKETGRAPH-ANTISPOOF_INCLUDE_DIR ${PG_ROOT}/antispoof)
	set(LIBPACKETGRAPH-ANTISPOOF_LIBRARY "${CMAKE_BINARY_DIR}/antispoof/libpacketgraph-antispoof.a")
	set(LIBPACKETGRAPH-ANTISPOOF_LIBRARY_SHARED "${CMAKE_BINARY_DIR}/libpacketgraph-antispoof.so")
	set(LIBPACKETGRAPH-ANTISPOOF_FOUND 1)
    return()
endif()

message ("PG_ANTISPOOF global variable not set, searching packetgraph-antispoof on the system ...")

find_path(LIBPACKETGRAPH-ANTISPOOF_ROOT_DIR
	NAMES include/packetgraph/packetgraph.h
)

find_path(LIBPACKETGRAPH-ANTISPOOF_INCLUDE_DIR
		NAMES antispoof.h
		HINTS ${LIBPACKETGRAPH-ANTISPOOF_ROOT_DIR}/include/packetgraph
)

set(LIBPACKETGRAPH-ANTISPOOF_NAME packetgraph-antispoof)

find_library(LIBPACKETGRAPH-ANTISPOOF_LIBRARY
		NAMES ${LIBPACKETGRAPH-ANTISPOOF_NAME}
		HINTS ${LIBPACKETGRAPH-ANTISPOOF_ROOT_DIR}/lib
)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(libpacketgraph-antispoof REQUIRED_VARS
		LIBPACKETGRAPH-ANTISPOOF_LIBRARY
		LIBPACKETGRAPH-ANTISPOOF_INCLUDE_DIR)
mark_as_advanced(
		LIBPACKETGRAPH-ANTISPOOF_ROOT_DIR
		LIBPACKETGRAPH-ANTISPOOF_LIBRARY
		LIBPACKETGRAPH-ANTISPOOF_INCLUDE_DIR
)
